spring.application.name=projeto-letramento
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.datasource.driver-class-name=

spring.jpa.database-platform=
spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=true

api.security.token.secret=